### PR TITLE
Updates on stylesheet

### PR DESCRIPTION
**Pull request by Acoolwolf96**
you can review and check if there are changes to be further made. I did some css and also i think there could be more features to add to the code, like a next button, the user can only see the next set of questions when they only refresh the page. A "Next" button will help resolve that issue and also if possible a page should take a certain number of questions instead of throwing in a bunch questions at once

### CODE REVIEW

**Comment by gibanator** [comment]
@Acoolwolf96 the css seems fine, but I didn't completely understand the 'Next' button idea
As I understand, now we have 5 random questions from each category (process, environment etc.) and you want to display like 5 questions simultaneously, am I right? If I am, that is a good idea, so the page doesn't seem overloaded.

@dadaJunglist also could you please kindly share your opinion on this (as you know better about the index.php page) and I think that it'd be better if one of you would resolve the conflicts as today I bit f'd up our main branch when i tried :)

**Comment by dadaJunglist** [comment]
The division of questionary to different pages is not a good thing at all. It is not a design decision which we will be able to complete in last 1/3 of the project. 2/3 of the project time is over and we should not change funcntional part at all. Best way to if design part would happen only with edititng css files and adding classes to elements if necessary. Currently how project works: on load of a index page we fetch questions and calculate submission with number of best answer from database, on press of the button we calculate variables to session's array and write things to database. On the results page. If you want to break page with questionary on 5, you will have to split functionallity that way, so calculation and processing will happen differently. If you are able to make it happen - do it, but don't wait help from on with this, I won't have enogh time to redo the project

**Comment by gibanator** [comment]
Andrejs is right i think.
> If you are able to make it happen - do it, but don't wait help from on with this

That's the main point - I too can't and don't want to do this, as I still have some stuff to do with results page. If you or others can do it - that will be great but this is not mandatory at all, I think

**Comment by dadaJunglist** [comment]
I think these changes could make us fail. At least, I won't be able to make needed changes in that time, considering also that we have work to do with completeing text response to the result page.

**Pull request closed without merging**
